# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OHoPaem_Et-8KsC30Y79D9E_vKAcwsjv
"""

# Getting sentences from the user
sentence1 = input('a: ') ; sentence2 = input('b: ')
count1 = 0; count2 = 0

dict1 = dict(); dict2 = dict()

# create dictionaries for two sentences as key: character and value:# of character exist in the sentences
for w in sentence1:
  dict1[w] = dict1.get(w,0) + 1

for w in sentence2:
  dict2[w] = dict2.get(w,0) + 1

# Find the different keys
for key in dict1.keys():
  if not key in dict2:    count1 +=1

for key in dict2.keys():
  if not key in dict1:    count2 +=1

# Find the common keys and compare the values.
common_keys = list(dict1.keys() & dict2.keys())

for w in common_keys:
  if (dict1[w] > dict2[w]):  count1 += dict1[w] - dict2[w]
  if (dict2[w] > dict1[w]):  count2 += dict2[w] - dict1[w]

if (count1 == 0) & (count2 == 0):
  print('they are anagrams')
else:
  print('remove %d characters from "%s" and %d characters from "%s"'%(count1, sentence1, count2, sentence2))