# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p9CSqJ7_tGnZFbeNstUIxxwx6stZmCME
"""

# import the necessary libraries
import pandas as pd
import sys
import os

# set the directory of csv files
#os.chdir('D:/Users/okanb/Desktop/interview/q2-top-seller')

# Load the csv files
sales_dataframe = pd.read_csv('sales.csv', delimiter=',')
product_dataframe = pd.read_csv('product.csv', delimiter=',')
store_dataframe = pd.read_csv('store.csv', delimiter=',')

start_date = str(); end_date= str(); rows = int()

if __name__ == "__main__":
  start_date = sys.argv[2]
  end_date = sys.argv[4]
  try:
    rows = int(sys.argv[6])
  except:
    rows = 3

#start_date = '2020-02-01'
#end_date= '2020-06-30'
#rows = 3

sales_dataframe['date'] = pd.to_datetime(sales_dataframe['date'])
mask_bool = (sales_dataframe['date']  >= start_date) & (sales_dataframe['date']  <= end_date)
sales_df = sales_dataframe.loc[mask_bool]

product_dict = dict() ; store_dict = dict()

for i in range(len(sales_df)):
  product_dict[sales_df.iloc[i]['product']] = product_dict.get(sales_df.iloc[i]['product'], 0) + sales_df.iloc[i]['quantity']

for i in range(len(sales_df)):
  store_dict[sales_df.iloc[i]['store']] = store_dict.get(sales_df.iloc[i]['store'], 0) + sales_df.iloc[i]['quantity']

list_quantity = list()
for i in range(0, len(product_dataframe)):
  list_quantity.append(product_dict[product_dataframe.loc[i, 'id']])

product_df = product_dataframe.copy()
product_df['quantity'] = list_quantity
product_df.sort_values(by='quantity', ascending=False, inplace=True)
#print(product_df)

product_series = product_df.groupby('quantity').quantity.count().sort_index()
pr_dict = dict(product_series)
df = pd.DataFrame(list(pr_dict.items()), columns=['name', 'count'])
df.sort_values(by='name', ascending=False, inplace=True)
df.reset_index(inplace=True)

count = int()
for i in range(rows):
  count += df['count'][i]

print('-- top seller product --')
print(product_df.iloc[range(0, count), [1, 3]].to_string(index=False))

list_quantity = list()
for i in range(len(store_dataframe)):
  list_quantity.append(store_dict[store_dataframe.loc[i, 'id']])

store_df = store_dataframe.copy()
store_df['quantity'] = list_quantity
store_df.sort_values(by='quantity', ascending=False, inplace=True)
#print(store_df)

store_series = store_df.groupby('quantity').quantity.count().sort_index()
st_dict = dict(store_series)
df = pd.DataFrame(list(st_dict.items()), columns=['name', 'count'])
df.sort_values(by='name', ascending=False, inplace=True)
df.reset_index(inplace=True)

count = int()
for i in range(rows):
  count += df['count'][i]

print('-- top seller store --')
print(store_df.iloc[range(0, count), [1, 3]].to_string(index=False))

brand_dict = dict()
for i in range(len(product_df)):
  brand_dict[product_df.iloc[i]['brand']] = brand_dict.get(product_df.iloc[i]['brand'], 0) + product_df.iloc[i]['quantity']
#print(brand_dict)

brand_df = pd.DataFrame(list(brand_dict.items()), columns=['brand', 'quantity'])
brand_df.sort_values(by='quantity', ascending=False, inplace=True)

brand_series = brand_df.groupby('quantity').quantity.count().sort_index()
br_dict = dict(brand_series)
df = pd.DataFrame(list(br_dict.items()), columns=['name', 'count'])
df.sort_values(by='name', ascending=False, inplace=True)
df.reset_index(inplace=True)

count = int()
for i in range(rows):
  count += df['count'][i]

print('-- top seller brand --')
print(brand_df.iloc[range(0, count), [0, 1]].to_string(index=False))

city_dict = dict()
for i in range(0 , len(store_df)):
  city_dict[store_df.iloc[i]['city']] = city_dict.get(store_df.iloc[i]['city'], 0) + store_df.iloc[i]['quantity']
#print(city_dict)

city_df = pd.DataFrame(list(city_dict.items()), columns=['city', 'quantity'])
city_df.sort_values(by='quantity', ascending=False, inplace=True)

city_series = brand_df.groupby('quantity').quantity.count().sort_index()
cty_dict = dict(city_series)
df = pd.DataFrame(list(cty_dict.items()), columns=['name', 'count'])
df.sort_values(by='name', ascending=False, inplace=True)
df.reset_index(inplace=True)

count = int()
for i in range(rows):
  count += df['count'][i]

print('-- top seller city --')
print(city_df.iloc[range(0, count), [0, 1]].to_string(index=False))

